[global]
   workgroup = WORKGROUP
   server string = Samba Server
   netbios name = blog
   security = user
   map to guest = bad user
   dns proxy = no

[BillySMBShare]
   path = /media/usb
   browsable = yes
   writable = no
   guest ok = yes
   read only = yes
   comment = Billy's USB Share
