# SSL cert SAN: secrethelpdesk934752.support.ciskom.pnc.ac.id
server {
    listen 80;
    server_name support.ciskom.pnc.ac.id;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name support.ciskom.pnc.ac.id;
    ssl_certificate     /etc/nginx/ssl/support.crt;
    ssl_certificate_key /etc/nginx/ssl/support.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    root /var/www/html/support;
    index index.html;
    location / { try_files $uri $uri/ =404; }
}
