user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Hide nginx version
    server_tokens off;

    # Needed for long domain names
    server_names_hash_bucket_size 128;

    # Default catch-all — return 444 for unknown hosts
    server {
        listen 80 default_server;
        listen 443 ssl default_server;
        ssl_certificate     /etc/nginx/ssl/main.crt;
        ssl_certificate_key /etc/nginx/ssl/main.key;
        return 444;
    }

    include /etc/nginx/conf.d/*.conf;
}
